# Generated by Django 6.0.3 on 2026-03-25 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial_academic_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('historical', models.JSONField(default=dict)),
                ('title', models.CharField(help_text='Lesson title', max_length=200)),
                ('content', models.TextField(help_text='Lesson content/description')),
                ('lesson_date', models.DateField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='academico.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'groups__name': 'Teachers'}, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lesson plan',
                'verbose_name_plural': 'lesson plans',
                'ordering': ['-lesson_date'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('historical', models.JSONField(default=dict)),
                ('value', models.DecimalField(decimal_places=2, help_text='Grade value (0-10)', max_digits=5)),
                ('term', models.IntegerField(choices=[(1, 'First Term'), (2, 'Second Term'), (3, 'Third Term'), (4, 'Fourth Term')])),
                ('grade_type', models.CharField(choices=[('exam', 'Exam'), ('assignment', 'Assignment'), ('project', 'Project'), ('participation', 'Participation')], default='exam', max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academico.academicyear')),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'Students'}, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academico.subject')),
            ],
            options={
                'verbose_name': 'grade',
                'verbose_name_plural': 'grades',
                'ordering': ['-term', 'subject__name'],
                'unique_together': {('student', 'subject', 'term', 'grade_type')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('historical', models.JSONField(default=dict)),
                ('is_present', models.BooleanField(default=False)),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'Students'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academico.lessonplan')),
            ],
            options={
                'verbose_name': 'attendance',
                'verbose_name_plural': 'attendances',
                'unique_together': {('student', 'lesson_plan')},
            },
        ),
    ]
