# Generated by Django 6.0.3 on 2026-03-25 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('historical', models.JSONField(default=dict)),
                ('relationship_type', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('other', 'Other')], default='guardian', max_length=20)),
                ('parent', models.ForeignKey(help_text='Parent or guardian user', limit_choices_to={'groups__name': 'Parents'}, on_delete=django.db.models.deletion.CASCADE, related_name='guardianships', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student user', limit_choices_to={'groups__name': 'Students'}, on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'guardian',
                'verbose_name_plural': 'guardians',
                'unique_together': {('parent', 'student')},
            },
        ),
    ]
